[project]
name = 'mining-reward-system'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.game-token]
path = 'contracts/game-token.clar'
clarity_version = 3
epoch = 3.1

[contracts.token-trait]
path = 'contracts/token-trait.clar'
clarity_version = 3
epoch = 3.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
